image: git.gfz-potsdam.de:5000/naaice/tug:ci

stages:
    - build
    - test
    - static_analyze

build_release:
  stage: build
  artifacts:
      paths:
          - build/test/testTug
      expire_in: 100s
  script:
      - mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DTUG_ENABLE_TESTING=ON ..
      - make -j$(nproc)

test:
    stage: test
    script:
        - ./build/test/testTug

lint:
  stage: static_analyze
  before_script:
    - apk add clang-extra-tools
  script:
    - mkdir lint && cd lint
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=cppcoreguidelines-*,clang-analyzer-*,performance-*, modernize-*" -DTUG_ENABLE_TESTING=OFF ..
    - make tug
  when: manual
