image: sobc/gitlab-ci

stages:
    - build
    - test
    - static_analyze

build_release:
  before_script:
    - apt-get update && apt-get install -y libeigen3-dev git
  stage: build
  artifacts:
      paths:
          - build/test/test
      expire_in: 100s
  script:
      - mkdir build && cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DBTCS_ENABLE_TESTING=ON ..
      - make -j$(nproc)

test:
    stage: test
    script:
        - ./build/test/test

lint:
  before_script:
    - apt-get update && apt-get install -y libeigen3-dev
  stage: static_analyze
  script:
    - mkdir lint && cd lint
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=cppcoreguidelines-*,clang-analyzer-*,performance-*,readability-*, modernize-*" -DBTCS_ENABLE_TESTING=OFF ..
    - make BTCSDiffusion
