image: sobc/gitlab-ci

stages:
    - build
    - test
    - static_analyze
    - dynamic_analyze

before_script:
    - apt-get update && apt-get install -y libeigen3-dev

build:
    stage: build
    artifacts:
        paths:
            - build/src/1D
            - build/src/2D
        expire_in: 100s
    script:
        - mkdir build && cd build
        - cmake ..
        - make

run_1D:
    stage: test
    dependencies: 
        - build
    script:
        - ./build/src/1D

run_2D:
    stage: test
    dependencies: 
       - build
    script:
        - ./build/src/2D

lint:
    stage: static_analyze
    script:
        - mkdir lint && cd lint
        - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=cppcoreguidelines-*,clang-analyzer-*,performance-*,readability-*, modernize-*" ..
        - make

memcheck_1D:
    stage: dynamic_analyze
    script:
        - cd build/src
        - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes ./1D 1>/dev/null

memcheck_2D:
    stage: dynamic_analyze
    script:
        - cd build/src
        - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes ./2D 1>/dev/null
