image: sobc/gitlab-ci

stages:
    - build
    - test

before_script:
    - apt-get update && apt-get install -y libeigen3-dev

build:
    stage: build
    script:
        - mkdir build && cd build
        - cmake ..
        - make

lint:
    stage: test
    script:
        - mkdir build && cd build
        - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-checks=cppcoreguidelines-*,clang-analyzer-*,performance-*,readability-*, modernize-*" ..
        - make
