#include "BTCSDiffusion.hpp" // for BTCSDiffusion, BTCSDiffusion::BC_DIRICHLET
#include <algorithm>         // for copy, max
#include <iostream>          // for std
#include <vector>            // for vector
using namespace std;

int main(int argc, char *argv[]) {

  // count of grid cells
  int x = 20;

  // create input + diffusion coefficients for each grid cell
  std::vector<double> alpha(x, 1 * pow(10, -1));
  std::vector<double> input(x, 1 * std::pow(10, -6));

  // create instance of diffusion module
  BTCSDiffusion diffu(x);

  // set the boundary condition for the left ghost cell to dirichlet
  diffu.setBoundaryCondition(0, 5. * std::pow(10, -6),
                             BTCSDiffusion::BC_DIRICHLET);

  // set timestep for simulation to 1 second
  diffu.setTimestep(1.);

  // loop 100 times
  // output is currently generated by the method itself
  for (int i = 0; i < 100; i++) {
    diffu.simulate(input, alpha);
  }

  return 0;
}
